#cloud-config
autoinstall:
  version: 1
  #############################################################################
  ## Configurations you probably won't change
  #############################################################################
  # A list of shell commands to invoke as soon as the installer starts, in particular before probing for block and network devices.
  # Replace the current autoinstall configuration with one provided by a trusted server
  early-commands:
    # - wget -O /autoinstall.yaml $TRUSTED_SERVER_URL
    - ping -c 1 google.com
  source:
    id: ubuntu-server-minimal
    # id: ubuntu-desktop-minimal
  locale: "en_US.UTF-8"
  keyboard:
    layout: us
  timezone: America/New_York
  refresh-installer: # Controls whether the installer updates to a new version before continuing, and if "true", which channel the update is downloaded from
    update: true # Update the installer before proceeding with installation; Can be either true or false
    channel: "stable/ubuntu-$REL" # Update from the stable channel (DEFAULT)
  codecs:    # Choose whether to install the ubuntu-restricted-addons package
    install: true
  drivers:   # Choose whether to install third-party drivers as suggested by `ubuntu-drivers`.
    # default behavior
    install: false
  reporting:
    builtin:
      type: print
  updates: all  # Controls the type of updates that will be downloaded and installed after system installation; Can be either "security" (for security updates only) or "all" (for all updates, like in this example).
  
  # shutdown instead of reboot
  shutdown: reboot
  error-commands:
    - tar -czf /installer-logs.tar.gz /var/log/installer/ # Collect all of the logs in /var/log/installer
    - journalctl -b > /installer-journal.log  # Collect the live system journal too

  #############################################################################
  ## Configurations you probably WILL change
  #############################################################################
  identity:
    hostname: server
    username: ubuntu
    # password: ubuntu
    password: $6$nKt.PUR5igrz8W8s$BcTOlGpY3N/ragXN2HpF.ONAP7MPqVNVbWcagHMBhlBasiY1IujA5VSBi31tDzR5sl5SySwYkMK8gzqr4B.Zm1

  ssh:
    install-server: true
    allow-pw: true
    # replace with the contents of the public key(s) as generated by
    # ssh-keygen or similar tools
    # - ssh-ed25519 AAAAC3NzaC..6O8tvZobj user@host
    authorized-keys: []

  packages:
    # Core CLI packages
    - git                   # version control system for source code
    - vim                   # terminal-based text editor
    - curl                  # command-line tool for HTTP/FTP requests
    - wget                  # command-line file downloader
    - unzip                 # extract .zip archives
    - tmux                  # terminal multiplexer (split panes, persistent sessions)
    - zsh                   # alternative shell with advanced features
    - fdupes                # find/log/delete file duplicates
    - nmap                  # scan local area network to find info about connected devices
    - speedtest-cli         # test internet upload/download speed from CLI
    - python-is-python3     # symlink: makes “python” run Python 3
    - ufw                   # Uncomplicated firewall, a user-friendly command-line tool for managing the system's iptables firewal
    - acl                   # Access Control List: a feature that provides a more fine-grained and flexible method for managing file and directory permissions than the traditional Unix owner, group, and others model
    - apt-utils

    # Desktop env packages
    # N/A
    
    # Server-only packages
    - nginx
    - gnupg                 # encryption/signing toolkit (GPG)
    - ca-certificates       # trusted SSL/TLS certificate bundle
  
  snaps:
    - name: hello-world
      channel: stable # Choose which channel to install the snap from (stable, candidate, beta, or edge) (DEFAULT)
      classic: false # Choose whether or not to use classic confinement (can be either true or false) (DEFAULT)

  late-commands:
    # This section runs right before the first reboot
    # You can't start systemd services yet. Just enable them and let them start on next reboot

    # Save installer logs from live session
    # subiquity-server-debug.log has a record of the commands run and their exit codes
    - curtin in-target -- echo "Saving installer logs to /target/var/log/installer-logs.tar.gz"
    - tar -czvf /target/var/log/installer-logs.tar.gz -C /var/log/installer/ .

    - curtin in-target -- echo "Success! Installation complete"
    # shut-down the host to avoid an infinite installer loop
    - shutdown -h now

  
  user-data:
    write_files:
      # System Wide. Affects all users. GitHub known_hosts so SSH to github.com doesn’t prompt
      - path: /etc/ssh/ssh_known_hosts
        append: true
        permissions: '644'
        owner: root:root
        content: |
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=

    runcmd:
      # - [eval, 'echo $(cat /proc/cmdline) "autoinstall" > /root/cmdline']
      # - [eval, 'mount -n --bind -o ro /root/cmdline /proc/cmdline']
      # - [eval, 'snap restart subiquity.subiquity-server']
      # - [eval, 'snap restart subiquity.subiquity-service']
      #############################################################################################
      #########             Bassam/ and /data Shortcuts
      #############################################################################################
      - echo "Creating bind mount for /data/username to /home/ubuntu/"
      - mkdir -p /data/ubuntu
      - mkdir -p /data/Media/
      - echo "/data/ubuntu /home/ubuntu/ none bind 0 0" >> /etc/fstab
      - mount --bind /data/ubuntu /home/ubuntu/
      # Allow me to write to /data
      - chown -R ubuntu:ubuntu /data
      - chmod 775 /data

      #############################################################################################
      #########             SSH
      #############################################################################################
      - echo "Enabling ssh"
      - systemctl enable ssh
      - systemctl start ssh

      - echo "Enabling firewall"
      - ufw enable

      - echo "Allow ssh through firewall"
      - ufw allow OpenSSH

      - echo "Allow nginx through firewall"
      - systemctl enable nginx
      - ufw allow 'Nginx Full'

      # Disable server falling asleep or hibernating
      - systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

      - shutdown -h now
